services:
  postgres:
    image: postgres:16-alpine
    container_name: pizza_postgres
    environment:
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: pizza_password
      POSTGRES_DB: pizza_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza_network

volumes:
  postgres_data:

networks:
  pizza_network:
    driver: bridge
