services:
  postgres:
    image: postgres:16-alpine
    container_name: pizza_postgres
    environment:
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: pizza_password
      POSTGRES_DB: pizza_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizza_user -d pizza_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pizza_redis
    ports:
      - "6379:6379"
    networks:
      - pizza_network

  backend:
    build:
      context: ./backend
    container_name: pizza_backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://pizza_user:pizza_password@postgres:5432/pizza_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - pizza_network

  frontend:
    build:
      context: ./frontend
    container_name: pizza_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - pizza_network


volumes:
  postgres_data:

networks:
  pizza_network:
    driver: bridge
