"""add payment fields to user and order

Revision ID: b86a01ecde85
Revises: a4ec0f8ac43c
Create Date: 2026-06-17 16:39:34.928248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b86a01ecde85"
down_revision: Union[str, Sequence[str], None] = "a4ec0f8ac43c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("payment_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("payment_method_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("payment_method_title", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "payment_method_title")
    op.drop_column("users", "payment_method_id")
    op.drop_column("orders", "payment_id")
    # ### end Alembic commands ###
